### ISSUE TITLE
vertical toolbar

### ISSUE THREAD

**Issue by mighelch** [Infocatcher/Custom_Buttons#32]
Can you adapt this button for vertical-toolbar addon?
https://addons.mozilla.org/en-US/firefox/addon/vertical-toolbar/
<img src="http://i.imgur.com/K7RhbZu.png"/>
As you can see when folder is opened, it covers the items below. Can you move it at the edge of vertical toolbar?

**Comment by Infocatcher** [comment]
I've added some corrections.
Also should be detected right-side vertical toolbar, but this detection is extension-specific (and will work only with Vertical Toolbar extension).

**Comment by mighelch** [comment]
Thanks works fine.

**Comment by mighelch** [comment]
Is it possible to disable "open on hover"? On vertical toolbar, when I click folder and go down in a rush to open a link, I often hit the folder below.

**Comment by Infocatcher** [comment]
> Is it possible to disable "open on hover"?

Currently only directly in code... For "Bookmarks Folder" button you can comment all that code:
```js
this.onmouseover = function(e) {
	if(e.target != this)
		return;
	Array.some(
		this.parentNode.getElementsByTagName("*"),
		function(node) {
			if(
				node != this
				&& node.namespaceURI == xulns
				&& node.boxObject
				// See https://github.com/Infocatcher/Custom_Buttons/issues/28
				//&& node.boxObject instanceof Components.interfaces.nsIMenuBoxObject
				&& "open" in node
				&& node.open
				&& node.getElementsByTagName("menupopup").length
			) {
				node.open = false;
				this.open = true;
				return true;
			}
			return false;
		},
		this
	);
};
```
Like following:
```js
/*
this.onmouseover = function(e) {
	...
};
*/
```

**Comment by mighelch** [comment]
Thank you.
