### ISSUE TITLE
[Purge tabs history] Stopped working, returns errors

### ISSUE THREAD

**Issue by Drugoy** [Infocatcher/Custom_Buttons#34]
```
TypeError: setWindowValue only accepts string values SessionStore.jsm:1770:0
NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS: [JavaScript Error: "setWindowValue only accepts string values" {file: "resource:///modules/sessionstore/SessionStore.jsm" line: 1770}]'[JavaScript Error: "setWindowValue only accepts string values" {file: "resource:///modules/sessionstore/SessionStore.jsm" line: 1770}]' when calling method: [nsISessionStore::setWindowValue] button.js:136:0
```

**Comment by Infocatcher** [comment]
Looks fixed for me after 06ca7532a6f7ea002dd8a82ed9be46ae3c4950c2 commit.

**Comment by Drugoy** [comment]
I'm still getting those errors + got an extra one (just once, in a few moments after the above errors appeared):
```
Content Security Policy: The page's settings blocked the loading of a resource at self ("default-src 'none'"). purgeTabsHistory.
```

An error about CSP makes me think that this may have something to do with NoScript. Though I'm not sure about that.
Also, turns out that the history gets actually purged, it's just 'go back' button remains visually the as when the tab has some history. Switching to another tab and then back - resets it's state properly.

**Comment by Infocatcher** [comment]
> I'm still getting those errors

Very strange... "setWindowValue only accepts string values" error should be gone after latest commit.

> Also, turns out that the history gets actually purged, it's just 'go back' button remains visually the as when the tab has some history. Switching to another tab and then back - resets it's state properly.

Hmm... directly called `UpdateBackForwardCommands(gBrowser.webNavigation);`, may be is needed some delay, but all work fine for me.

**Comment by Drugoy** [comment]
Damn, I forgot that updating code from the initialization section requires a browser restart.
Everything is fine now: no errors in the console, and 'go back' button gets updated instantly.

**Comment by Infocatcher** [comment]
> I forgot that updating code from the initialization section requires a browser restart.

Not always, there is `onDestroy` function for such purposes. May be something went wrong with Custom Buttons itself...

> Everything is fine now: no errors in the console, and 'go back' button gets updated instantly.

Great!
