### ISSUE TITLE
[Custom Buttons: Source Editor] Stopped working after "Copy to Clipboard" command in context menu of any button.

### ISSUE THREAD

**Issue by Halibut80** [Infocatcher/Custom_Buttons#40]
In console
```
22:18:45.862 NS_ERROR_UNEXPECTED: 
anonymous/watcher.initWindow()button.js:186
anonymous/watcher.handleEvent()button.js:653
button.js:186

```

Win 8.1 x64, FF Nightly x64 48.0a1 BuildID:20160419030312, e10s disabled.

**Comment by Infocatcher** [comment]
See http://custombuttons.sourceforge.net/forum/viewtopic.php?f=5&t=3720
Some weird things may happens with built-in `DOMParser()` in Firefox 45+.

**Comment by Halibut80** [comment]
Спасибо. Должен ли я закрыть баг, раз проблема в самом расширении?

**Comment by Infocatcher** [comment]
Я закрою, да. Править все равно в расширении.
Хотя как по мне – это в Firefox наломали...
