### ISSUE TITLE
[Attributes_Inspector] document.tooltipNode don't work

### ISSUE THREAD

**Issue by sdavidg** [Infocatcher/Custom_Buttons#51]
Attributes_Inspector version 0.3.3.2 - 2020-03-14
FF 91.0.2 (64-bit)

Personalized tooltips don't work on this Firefox version

**Comment by Infocatcher** [comment]
As I see, this bus is actually about **Undo Close Tabs** button, should be fixed now: https://github.com/Infocatcher/Custom_Buttons/commit/dc52eeaff6f55ae548001701b2f303bf92db1196

**Comment by sdavidg** [comment]
You are right, this issue is about version 0.3.3.2 - 2020-03-14 **Undo Close Tabs**. Works fine, thanks.
