### ISSUE TITLE
0.1.2pre13 блокирует открытие ссылки в новой вкладке колёсиком

### ISSUE THREAD

**Issue by VicDobrov** [Infocatcher/Custom_Buttons#52]
extDevTools.js — код в строках 375-387 блокирует стандартный функционал Firefox - открытие ссылки в новой вкладке кликом средней кнопки мыши:
`addEventListener("command", function(e) { // Prevent middle-click commands in Firefox 89+…`

Моя система — Arch Linux, версия Firefox 88.0.1

**Comment by Infocatcher** [comment]
Предполагаю, что для запуска используется что-то отличное от Custom Buttons, соответственно, функция `addEventListener()` не переопределена и слушатель событий вешается на кнопку, а на `[window.]addEventListener()`.
